# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cr_estim <- function(Y, Delta, X) {
    .Call('_PTDA_cr_estim', PACKAGE = 'PTDA', Y, Delta, X)
}

#' @export
boot_estim <- function(Y, Delta, X, boot_replicate = 1000L, n_boot_gene = 100L) {
    .Call('_PTDA_boot_estim', PACKAGE = 'PTDA', Y, Delta, X, boot_replicate, n_boot_gene)
}

